name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          docker images -a
          
  deploy:

    runs-on: self-hosted
    environment: dev

    steps:
    - name: Print the Docker image
      run: |
          echo my-image-name:$(date +%s)
